name: Andrew Feitlinger
exclude: ['CNAME', 'README.md']
timezone: UTC
show_drafts: true
pygments: true
permalink: /posts/:year/:month/:day/:title
markdown: kramdown
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..2
    smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
    use_coderay: false
