name: Andrew Feitlinger
exclude: ['CNAME', 'README.md']
timezone: UTC
show_drafts: true
pygments: true
permalink: /blog/:title
markdown: kramdown
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..4
    smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
    use_coderay: false
coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
